// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ----------------------------------------------------------------------------
'use strict';

export enum TelemetryEvent {
    AccountContextManager_GetKubeconfigPathError = "account-context-manager-get-kubeconfig-path-error",
    Activation = "activation",
    BinariesUtility_CheckIfBinaryExistsError = "binaries-utility-check-if-binary-exists-error",
    BinariesUtility_CleanUpBeforeDownloadError = "binaries-utility-cleanup-before-download-error",
    BinariesUtility_CopyKubectlToBridgeFolderError = "binaries-utility-copy-kubectl-to-bridge-folder-error",
    BinariesUtility_CopyKubectlToBridgeFolderSuccess = "binaries-utility-copy-kubectl-to-bridge-folder-success",
    BinariesUtility_DeleteLegacyBridgeDownloadDirectoryError = "binaries-utility-delete-legacy-bridge-download-directory-error",
    BinariesUtility_DeleteLegacyBridgeDownloadDirectorySuccess = "binaries-utility-delete-legacy-bridge-download-directory-success",
    BinariesUtility_DownloadError = "binaries-utility-download-error",
    BinariesUtility_EnsureBinariesError = "binaries-utility-ensure-binaries-error",
    BinariesUtility_FileDownloaderVersionError = "binaries-utility-file-downloader-version-error",
    BinariesUtility_OverallDownloadStatus = "binaries-utility-overall-download-status",
    BinariesUtility_TryGetBinariesError = "binaries-utility-try-get-binaries-error",
    BinariesVersionClient_GetCachedBinariesDownloadInfoError = "binaries-version-client-get-cached-binaries-download-info-error",
    BinariesVersionClient_GetCachedBinariesDownloadInfoSuccess = "binaries-version-client-get-cached-binaries-download-info-success",
    BinariesVersionClient_GetDownloadInfoError = "binaries-version-client-get-download-info-error",
    BinariesVersionClient_GetDownloadInfoSuccess = "binaries-version-client-get-download-info-success",
    BridgeClient_CheckCredentialsError = "cli-client-check-credentials-error",
    BridgeClient_CleanLocalConnectError = "cli-client-clean-local-connect-error",
    BridgeClient_ConnectError = "cli-client-connect-error",
    BridgeClient_GetVersionError = "cli-client-get-version-error",
    BridgeClient_PrepConnectError = "cli-client-prep-connect-error",
    BridgeClient_RefreshCredentialsError = "cli-client-refresh-credentials-error",
    BridgeClient_RefreshCredentialsOutputError = "cli-client-refresh-credentials-output-error",
    BridgeClient_RefreshCredentialsSuccess = "cli-client-refresh-credentials-success",
    CliVersionsClient_GetDownloadInfoError = "cli-versions-client-get-download-info-error",
    CliVersionsClient_GetDownloadInfoStatus = "cli-version-client-get-download-info-status",
    ConfigureCommandError = "configure-command-error",
    ConfigureCommandTriggered = "configure-command-triggered",
    Connect_DebugSessionStarted = "connect-debug-session-started",
    Connect_EnsureConfigurationPresentCancelled = "connect-ensure-configuration-present-cancelled",
    Connect_EnsureConfigurationPresentError = "connect-ensure-configuration-present-error",
    Connect_Error = "connect-error",
    Connect_ServiceList = "connect-service-list",
    Connect_StartConnect = "connect-start-connect",
    Connect_StatusBarMenuConnectError = "connect-status-bar-menu-connect-error",
    Connect_TerminalLaunched = "connect-terminal-launched",
    Connect_UnsupportedOperatingSystemError = "connect-unsupported-operating-system-error",
    Connect_ValidateNonDevSpacesCluster = "connect-validate-non-dev-spaces-cluster",
    Connect_WizardError = "connect-wizard-error",
    Connect_WrongKubeconfigContextTargetedModalClosed = "connect-wrong-kubeconfig-context-targeted-modal-closed",
    ConnectInitializationError = "connect-initialization-error",
    ConnectPreLaunchTaskSkipped = "connect-pre-launch-task-skipped",
    ConnectServiceTaskTerminal_Error = "connect-service-task-terminal-error",
    ConnectServiceTaskTerminal_StartConnect = "connect-service-task-terminal-start-connect",
    DebugLocalTunnel_CommandPaletteSelected = "debug-local-tunnel-command-palette-selected",
    DebugLocalTunnel_DeploymentSelected = "debug-local-tunnel-deployment-selected",
    DebugLocalTunnel_JobSelected = "debug-local-tunnel-job-selected",
    DebugLocalTunnel_PodSelected = "debug-local-tunnel-pod-selected",
    DebugLocalTunnel_ServiceSelected = "debug-local-tunnel-service-selected",
    DebugLocalTunnel_UnknownNodeSelected = "debug-local-tunnel-unknown-node-selected",
    DebugLocalTunnel_UnknownResourceSelected = "debug-local-tunnel-unknown-resource-selected",
    DotNetClient_GetVersionError = "dotnet-client-get-version-error",
    KubeConfigCredentialsManager_RefreshCredentialsError = "kubeconfig-credentials-manager-refresh-credentials-error",
    KubectlClient_AllFqdnsRetrievalError = "kubectl-client-all-fqdns-retrieval-error",
    KubectlClient_CommandError = "kubectl-client-command-error",
    KubectlClient_CurrentContextRetrievalError = "kubectl-client-current-context-retrieval-error",
    KubectlClient_GetNamespacesError = "kubectl-client-get-namespaces-error",
    KubectlClient_GetVersionError = "kubectl-client-get-version-error",
    KubectlClient_GetPodNameError = "kubectl-client-get-pod-name-error",
    KubectlClient_GetNamespaceError = "kubectl-client-get-namespace-error",
    KubectlClient_GetContainerListError = "kubectl-client-get-container-list-error",
    KubernetesPanelCustomizer_ApiUnavailableError = "kubernetes-panel-customizer-api-unavailable-error",
    UnexpectedError = "unexpected-error",
    UnsupportedTargetResourceType = "unsupported-target-resource-type",
}