name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "16.20.1"
      - name: Build Extension
        run: |
          npm install
          npm run compile
      - name: Smoke test (Linux)
        run: xvfb-run -a npm run test
        if: runner.os == 'Linux'
      - name: Smoke test (Mac, Windows)
        run: npm run test
        if: runner.os != 'Linux'
      - name: Package Extension
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run vscode:package
          mkdir vsix
          mv *.vsix vsix
      - name: Archive Extension
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: vsix
          path: vsix
